### ISSUE TITLE
can not install package

### ISSUE THREAD

**Issue by vodanh86** [venkatesanchinna/yii2-livechat#1]
Dear, 
When I run "php composer.phar require --prefer-dist venkaetsangee/yii2-livechat". I got 
" [InvalidArgumentException]
 Could not find package venkaetsangee/yii2-livechat at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability"
Can you check

**Comment by venkatesanchinna** [comment]
Hi
The installation process has been updated. now you can install.

**Comment by vodanh86** [comment]
Dear Venkatesanchinna,
I still got the previous problem. 
" [InvalidArgumentException]
 Could not find package venkaetsangee/yii2-livechat at any version for your  minimum-stability (stable). Check the package spelling or your minimum-stability"
Can you check again?

**Comment by venkatesanchinna** [comment]
Hi

Can you run this
composer require venkatesanchinna/yii2-livechat
I have installed in my project its working

**Comment by vodanh86** [comment]
Thank you so much
